### ISSUE TITLE
naming convection tiryoh/ros2-desktop-vnc:humble-arm64-20220921T0434 

### ISSUE THREAD

**Issue by mahesh11T** [Tiryoh/docker-ros2-desktop-vnc#124]
can you explain this naming convection? 20220921T0434

https://hub.docker.com/r/tiryoh/ros2-desktop-vnc

is there a built version for 20.04 ubuntu focal ros2?

**Comment by Tiryoh** [comment]
> can you explain this naming convection? 20220921T0434

This is a timestamp based on the built time. `YYYYMMDDTHHmm`

> is there a built version for 20.04 ubuntu focal ros2?

There is a foxy version pre-build image. You can use with : `docker run -p 6080:80 --shm-size=512m tiryoh/ros2-desktop-vnc:foxy`

**Comment by mahesh11T** [comment]
> > can you explain this naming convection? 20220921T0434
> 
> This is a timestamp based on the built time. `YYYYMMDDTHHmm`
> 
> > is there a built version for 20.04 ubuntu focal ros2?
> 
> There is a foxy version pre-build image. You can use with : `docker run -p 6080:80 --shm-size=512m tiryoh/ros2-desktop-vnc:foxy`

oh ok, thanks, but sorry for this unrelated question, I was actually trying to use isaac sim inside docker-desktop windows, i have no luck, do you have any experience with it? 
https://docs.omniverse.nvidia.com/isaacsim/latest/installation/install_container.html 

![image](https://github.com/Tiryoh/docker-ros2-desktop-vnc/assets/107621428/45c9eda1-6eec-4561-8022-f2ff3f027279).

**Comment by Tiryoh** [comment]
I don't know much about Omniverse, but this project is not suitable for use with NVIDIA devices.
The following project may be of use to you.
https://github.com/atinfinity/nvidia-egl-desktop-ros2

**Comment by Tiryoh** [comment]
Due to inactivity, I'm closing this issue. Feel free to reopen it if needed.
