### ISSUE TITLE
Network Mode:host breaks the VNC connection

### ISSUE THREAD

**Issue by alex77272** [Tiryoh/docker-ros2-desktop-vnc#138]
Is there a way to run the Docker in network_mode:host? Rather than the default bridge mode? When I do that, I can't connect to the VNC desktop viewer anymore.

**Comment by alex77272** [comment]
Wow, your help was incredibly valuable. Thank you for solving the Git issue. I've been struggling with it for hours and your guidance has made all the difference. I wish you all the best and once again, thank you so much.

Alex

**Comment by Tiryoh** [comment]
@XO30 Thanks for your support!
