### ISSUE TITLE
USB access

### ISSUE THREAD

**Issue by samuk** [Tiryoh/docker-ros2-desktop-vnc#167]
I'm trying to run https://github.com/hippo5329/linorobot2_hardware I need to flash my ESP32 over serial/USB

Could you add forwards for [ttyUSB0 & ttyACM0](https://www.homeautomationguy.io/blog/docker-tips/accessing-usb-devices-from-docker-containers) it wouldn't work for all use cases, but many I think

**Comment by Tiryoh** [comment]
maybe you can try to run adding `--device=/dev/ttyUSB0 --device=/dev/ttyACM0` options like this:

```
docker run -p 6080:80 --security-opt seccomp=unconfined --shm-size=512m --device=/dev/ttyUSB0 --device=/dev/ttyACM0 tiryoh/ros2-desktop-vnc:humble
```
