### ISSUE TITLE
Add code editor

### ISSUE THREAD

**Issue by Tiryoh** [Tiryoh/docker-ros2-desktop-vnc#62]
options
* https://github.com/coder/code-server

ref: https://github.com/hsr-project/tmc_wrs_docker

**Comment by takasehideki** [comment]
I want to suggest VSCodium, which avoids licensing issues from VS Code.
https://vscodium.com/

This has been used in AI-Robot-Book.
https://github.com/AI-Robot-Book/docker-ros2-desktop-ai-robot-book/blob/ai-robot-book/Dockerfile.amd64#L158-L168
