### ISSUE TITLE
Browser does not work

### ISSUE THREAD

**Issue by jmguerreroh** [Tiryoh/docker-ros2-desktop-vnc#65]
In humble and rolling versions:

Google chrome browser does not work. The icon appears but it is not installed. You should install it downloading using wget and after use option --no-sandbox. Could it be fixed? Maybe installing Firefox correctly, it seems to be installed but it doesn't work either.

Thank you!

**Comment by Tiryoh** [comment]
It seems like working on Ubuntu 20.04.4 + Docker version 20.10.17, build 100c701

Could you tell me how to reproduce it?

![Screenshot from 2022-09-20 20-51-40](https://user-images.githubusercontent.com/3256629/191250405-c42fdfce-5461-4e38-84bd-4dcd2312d09f.png)

**Comment by jmguerreroh** [comment]
My machine:
Description:	Ubuntu 22.04.1 LTS
Docker version 20.10.18, build b40c2f6

I tried different TAGs: humble-amd64, rolling-amd64, and humble-20220911T0542 running as: "docker run -p 6080:80 tiryoh/ros2-desktop-vnc:TAG" and I have the same problem in all versions.

Am I doing something wrong?

**Comment by jmguerreroh** [comment]
> `--security-opt seccomp=unconfined` flag is required to launch humble and rolling image. See #56.
> 
> I guess starting the container with the following command may fix the problem.
> 
> ```
> docker run -p 6080:80 --shm-size=512m --security-opt seccomp=unconfined tiryoh/ros2-desktop-vnc:humble-amd64
> ```

Thank you! It works like a charm.
