### ISSUE TITLE
Suggestion: add terminator

### ISSUE THREAD

**Issue by takasehideki** [Tiryoh/docker-ros2-desktop-vnc#71]
I think "[terminator](https://gnome-terminator.org/)" is an essential tool for ROS developers🤖 
Of course the user can install it later if necessary, but for hands-on use of this Docker environment, it is very convenient to have it installed from the beginning.
What do you think about adding this?

**Comment by Tiryoh** [comment]
Good idea!

**Comment by Tiryoh** [comment]
Added in https://github.com/Tiryoh/docker-ros2-desktop-vnc/pull/73.
Thanks @takasehideki :+1:

**Comment by takasehideki** [comment]
Thanks for adding!
I should have sent a PR, but I apologize for not getting around to it ;(

**Comment by Tiryoh** [comment]
No problem at all! 😄
