### ISSUE TITLE
Suggestion: enable auto completion in docker container

### ISSUE THREAD

**Issue by atinfinity** [Tiryoh/docker-ros2-desktop-vnc#77]
I suggest to enable auto completion in docker container.

```diff
+ RUN rm /etc/apt/apt.conf.d/docker-clean
```

## Reference

- https://github.com/tianon/docker-brew-ubuntu-core/issues/75#issuecomment-386444576
- https://penguin-coffeebreak.com/archives/242

**Comment by Tiryoh** [comment]
Thanks! I'll merge it after fixing CI 👍

**Comment by Tiryoh** [comment]
Added in https://github.com/Tiryoh/docker-ros2-desktop-vnc/pull/79.
Thanks @atinfinity  :+1:
