### ISSUE TITLE
Suggestion: enable colcon-argcomplete

### ISSUE THREAD

**Issue by atinfinity** [Tiryoh/docker-ros2-desktop-vnc#78]
I suggest to enable colcon-argcomplete in docker container. 

## Reference

- https://colcon.readthedocs.io/en/released/user/installation.html#enable-completion
- https://hans-robo.hatenablog.com/entry/2020/04/10/213009

**Comment by Tiryoh** [comment]
Added in https://github.com/Tiryoh/docker-ros2-desktop-vnc/pull/80.
Thanks @atinfinity  :+1:
