### ISSUE TITLE
Suggestion: add web browser

### ISSUE THREAD

**Issue by atinfinity** [Tiryoh/docker-ros2-desktop-vnc#97]
The desktop switched to Ubuntu Mate by <https://github.com/Tiryoh/docker-ros2-desktop-vnc/pull/92>.
On the other hands, web browser was not installed.
So, I suggest to add web browser.

- Firefox
- Chrome
- Chromium etc...

**Comment by Tiryoh** [comment]
Great, thanks for pointing this out!
